version: '3.8'
services:
  go-db:
    image: postgres:13
    ports:
      - 1337:1337
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: go
    networks:
      - go-backend
networks:
  go-backend: