# service name
service: app

# version contraint
frameworkVersion: '3'

provider:
  name: aws
  # runtime: go1.x
  stage: local
  region: us-east-1

custom:
  serverless-offline:
    noPrependStageInUrl: true

package:
  exclude:
    - ./**
  include:
    - ./bin/**

# functions: 

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        KeySchema:
          - AttributeName: Username
            KeyType: HASH